### ISSUE TITLE
Certus Quartz from Applied Energetics Crashes chunks

### ISSUE THREAD

**Issue by kanimaru** [red2blue/AQM2#11]
[crash-2021-12-16_02.42.43-client.txt](https://github.com/red2blue/AQM2/files/7723991/crash-2021-12-16_02.42.43-client.txt)
Getting it from a gold chest into player inventory does crash the client and clients in the area. 
Since 1.3.2.
Multiplayer Server

**Comment by Adney467** [comment]
i have the same problem but i download the ticking entity fix from discord and that fix the crash but somehow when u are holding the certus quartz, u will just freeze and cant open inventory

**Comment by Adney467** [comment]
so i reported it in the official discord, and apparently the bug is caused by an entity called "Ender Clocked Lethargic Draning Creeper"

**Comment by kanimaru** [comment]
Seems to work in meanwhile.
