### ISSUE TITLE
Unable to Join a AQM2 server due to crash

### ISSUE THREAD

**Issue by choff10** [red2blue/AQM2#13]
**Modpack Version**
AQM2 1.4.1

**Minecraft Version**
1.18

**Describe the bug**
As soon as I join the world it crashes. I was working on putting an item into a barrel.

**Expected behavior**
Should be able to load in and go back to what I was working on however I never have a chance to do anything. 

**Crash log or latest.log.log**
(https://pastebin.com/4C9xGLWu)

**Additional context**
Our server has been experiencing multiple crashes that are frequent.

**Comment by red2blue** [comment]
Rendering issues. try disabling shaders before joining
