### ISSUE TITLE
[BUG] Can't run Server as a Daemon Process

### ISSUE THREAD

**Issue by dallasgreene** [red2blue/AQM2#146]
**Modpack Version**
2.0.5.1

**Minecraft Version**
1.18.1

**Describe the crash or bug**
Whenever I run `java -jar fabric-server-launch.jar` in a terminal (ssh'd into AWS), the server starts successfully and stays up, I can connect and play.
Whenever I try to get that same command to run as a daemon, it starts successfully, but then immediately stops and gracefully shuts down. Exit code 0.

**Steps to reproduce the behavior:**
```
[Unit]
Description=Minecraft Service
After=networking.service

[Service]
Type=simple
User=ec2-user
WorkingDirectory=/minecraft
ExecStart=/usr/bin/java -jar /minecraft/fabric-server-launch.jar

[Install]
WantedBy=multi-user.target
```
Download the server-starter zip to /minecraft on a linux system. Run the startserver.sh from terminal, until the server is successfully created. Create this file at `/etc/systemd/system/mc-server.service` on a linux system, and run it with `systemctl start mc-server`.

**Expected behavior**
Server should start up and remain up, they way it does when I run it from the terminal.

**Additional context**
The logs from the daemon look exactly the same as if I ran it in the terminal, waited for it to start up, and then entered ctrl + c. It logs itself stopping and saving before exiting 0.

Does the server process need to be connected to a valid stdin for some reason? I can't think of any other reason why it would be behaving differently running as a service vs running in the terminal.

**Comment by dallasgreene** [comment]
I've tried using rc.local to run the server as well, and I still get this behavior where it stops gracefully immediately after starting, so it doesn't seem to be an issue with systemd.

If anyone has configured a server and knows a different way of getting the jar to run on startup, that's all I'm trying to do.

**Comment by itsdinkd** [comment]
Wish I could help, but this is above my scope of knowledge. I'll leave this open though in case someone can help. 

You might be better off posting this in the github for the creators of Server-Start though https://github.com/BloodyMods/ServerStarter/issues

**Comment by dallasgreene** [comment]
Thanks for your response, after investigating further it looks like the server runs a sort of interactive shell so that you can enter commands. When it runs as a service and stdin is null (it might send an EOF or something, I’m unsure) the server stops itself because the interactive shell isn’t attached to anything. Closing this because I’m sure this is out of the scope of this modpack, I’ll try to bring this up to ServerStarter.
