### ISSUE TITLE
[BUG] Cannot place/equip Artifality's Ukulele or Balloon on back 

### ISSUE THREAD

**Issue by vik2or** [red2blue/AQM2#147]
**Modpack Version**
v2.0.6

**Minecraft Version**
1.18.1

**Describe the crash or bug**
I can't place the ukulele or balloon  on any back slot (backpack, armor, cape, cosmetic)

**Steps to reproduce the behavior:**
Just get an ukulele/balloon from Artifanity mod and try to equip it on your back

**Expected behavior**
When i click on the backpack slot it should place the ukulele/balloon there.

**Screenshots**
![2022-02-25_16 45 35](https://user-images.githubusercontent.com/3966571/155735355-82ff35f0-ffa8-4fdb-8ab1-6111fe6bc68e.jpg)

**Crash log or latest.log.log**
https://pastebin.com/azRzZezh

**Comment by itsdinkd** [comment]
Put it in your hot bar, and sneak right click. It will be equipped automatically if it can.
