### ISSUE TITLE
[BUG] Blast furnace estimation inconsistency

### ISSUE THREAD

**Issue by NyarlathotepZERO** [red2blue/AQM2#148]
**Modpack Version**
AQM 2 - 2.0.5.1

**Minecraft Version**
1.18

**Describe the crash or bug**
Blast furnace estimated parts/time is not consistent with actual output in end product

**Steps to reproduce the behavior:**
--not sure if it is just bronze or inconsistent with all products, but these are the steps that I took.
1. drop lava bucket in blast furnace
2. check estimated product by mousing over the flames
3. drop bronze dust in the input according to the amount it estimates
4. wait until near the end and notice that the amount it has produced vs its initial estimation is wildly different

**Expected behavior**
When mousing over the estimate, I would expect that the amount of items it estimates as being able to smelt would be consistent with the amount it actually produces

**Screenshots**
![image](https://user-images.githubusercontent.com/26475624/155801864-6dce3685-3f55-4ff4-bc6a-68f83be5504e.png)

**Crash log or latest.log.log**
-

**Additional context**
-

**Comment by itsdinkd** [comment]
Does this occur in 6.0.2a?

**Comment by NyarlathotepZERO** [comment]
> Does this occur in 6.0.2a?

Negative, this can be closed.
