### ISSUE TITLE
[BUG] Bewitchment book not loading at all since 2.0.5.1 update

### ISSUE THREAD

**Issue by BinxetyBinx** [red2blue/AQM2#149]
AQM2 2.0.5.1 on Fabric 1.18.1

This issue I reported to Bewitchment dev, they reported back that this is on AQM.

https://github.com/MoriyaShiine/bewitchment/issues/257

**Comment by serverinspector** [comment]
I can vouch to this.

**Comment by BinxetyBinx** [comment]
> I can vouch to this.

I've seen at least 4 people, 5 if you include myself, in the AQM discord the past day and a half talking about having the same problem.

**Comment by itsdinkd** [comment]
Fixed with v2.1
