### ISSUE TITLE
Multiple products for smelting calcite blocking all progression[BUG]

### ISSUE THREAD

**Issue by Zavender9** [red2blue/AQM2#15]
**Modpack Version**
1.4.2 Hotfix
**Minecraft Version**
1.18.1
**Describe the bug**
Smelting Calcite (vanilla block) can produce two outputs, Smooth Calcite From Consistency Plus or Polished Calcite from Spectrum. Smelting it seems to only provide smooth calcite, which is unable to be used in recipes from Spectrum, including the base workbench. This makes the mod unplayable past collecting the book.

**To Reproduce**
Literally just smelt calcite in a vanilla furnace. The product is unable to be used to make a simple recipe like the "Pigment Pedestal" from spectrum. 

**Expected behavior**
Smelting should give Polished Calcite, or Smooth Calcite should be in some form of oredict so it can be used for Spectrum (as it literally has a 1 to 1 cost of 1 smelt, same as Polished).

**Screenshots**
![image](https://user-images.githubusercontent.com/78673306/147377465-f7509878-bc48-4ff3-9976-ac4550928a00.png)

**Crash log or latest.log.log**
N/A

**Additional context**
Simple problem but literally stopping all progress into spectrum. Kind of high priority.

**Comment by red2blue** [comment]
Fixed in 1.4.4. Thank you for posting
