### ISSUE TITLE
[Feature Request] disable third person in elytra flight

### ISSUE THREAD

**Issue by cadpri** [red2blue/AQM2#151]
**Is your feature request related to adding/removing a mod or is it a ingame suggestion.**
Is it possible to remove third person in elytra flight? 

**Why do we need this feature?**
Because everyone just dies when landing because the elytra steering is totally messed up compared to first person flight.

**Link to the modpage if mod?**
I don't known which mod makes that

**Additional context**

**Comment by KindaLesbi** [comment]
Just being able to swap between 1st and 3rd person while flying would be nice. Makes it a bit difficult for Advanced Cave Exploration, as well as combative flight. I adore it for long distance travel, but it'd be nice to see a toggle for it so it wouldn't keep forcing you back and forth.

**Comment by TheSheev** [comment]
If you install [Kiwi](https://www.curseforge.com/minecraft/mc-mods/kiwi-fabric), when you next launch the game, it will create a config for Nimble (The mod that does 3rd person elytra). From there you can disable it on your end.

**Comment by itsdinkd** [comment]
Not really a feature since it's already featured. You can try what Sheev mentioned, or edit the nimble config.

**Comment by TheSheev** [comment]
> edit the nimble config.

The nimble config doesn't appear unless kiwi is installed. ;)
Per Nimble's mod page:
> Client-side only. All these features can be disabled or configured if you have installed Kiwi (Fabric).
