### ISSUE TITLE
myLoot Suggestion

### ISSUE THREAD

**Issue by FooterManDev** [red2blue/AQM2#152]
**Is your feature request related to adding/removing a mod or is it a ingame suggestion.**
myLoot addition to the modpack.

**Why do we need this feature?**
myLoot is like Lootr, it makes most loot chests in structures per-player, so one loot chest can be claimed by multiple people. 

**Link to the modpage if mod?**
(https://www.curseforge.com/minecraft/mc-mods/myloot)

**Additional context**
(Nothing else)

**Comment by itsdinkd** [comment]
I'm already aware and plan on using it once more updates came out. It's new so I'm waiting for bugs to be ironed out.
