### ISSUE TITLE
[BUG] "The Graveyard" blocks not categorized per their Vanilla equivalent tags

### ISSUE THREAD

**Issue by TheSheev** [red2blue/AQM2#154]
**Modpack Version**
2.0.6a

**Minecraft Version**
1.18.1

**Describe the crash or bug**
The Graveyard adds it's own vanilla blocks (Deepslate, Grass Block, Moss Block, Stone, Andesite, Granite, Diorite, Tuff, Dirt, Coarse Dirt, Rooted Dirt, & Podzol) which do not stack with Vanilla equivalents, or are categorized correctly to work with features such as Shulks ability to break stone without tools.

**Steps to reproduce the behavior:**
See above & Below

**Expected behavior**
See above & Below

**Screenshots**
![2022-02-28_21 08 29](https://user-images.githubusercontent.com/89590514/156094955-fd49bf74-2138-42e9-bcd1-67724d5628fb.png)

https://user-images.githubusercontent.com/89590514/156095323-77ff87ef-9756-4f1d-b69e-e5b026b06085.mp4

https://user-images.githubusercontent.com/89590514/156095729-be09c74a-a13e-43f4-ac99-037e4d586e35.mp4

**Crash log or latest.log.log**
N/A

**Additional context**
Solution If possible, use kubejs to replace Graveyard blocks with vanilla ones?

**Comment by itsdinkd** [comment]
can't do much about replacing them with the vanilla version, however, I added the blocks into the tag that origins uses for natural stone. shulks should be able to break them on the update

**Comment by TheSheev** [comment]
@itsdinkd Seems that changed messed up the original tag from Origins or something. See #199

**Comment by itsdinkd** [comment]
It was fixed Sheev
