### ISSUE TITLE
Phantom suffocates when not supposed to due to lithium

### ISSUE THREAD

**Issue by serverinspector** [red2blue/AQM2#155]
**Modpack Version**
latest

https://github.com/apace100/origins-fabric/issues/473

A simple config change can fix it, I don't know if it is configured right to avoid this bug client-side. But it is not server-side configured.

**Comment by itsdinkd** [comment]
Thanks for the heads up. However, this would be something individual server owners/single players would have to do. I'm not going to set an entire optimization feature off by default for phantoms.
