### ISSUE TITLE
Is there a Chance to get Refiend Storage in this modpack?

### ISSUE THREAD

**Issue by Knuckels92** [red2blue/AQM2#156]
**Is your feature request related to adding/removing a mod or is it a ingame suggestion.**
I dont like Applied Energistics at all, its so Much less Fun than Refined Storage

**Why do we need this feature?**
Refined Storage is for me a Much better Storage System and the Preformance is better

**Link to the modpage if mod?**
https://www.curseforge.com/minecraft/mc-mods/refined-storage

**Comment by busterbrown1999** [comment]
Refined Storage is a great mod but unfortunately not available for fabric at this time.

**Comment by Knuckels92** [comment]
But there is the RS2 for Fabric, relesed couple days ago ;)

**Comment by busterbrown1999** [comment]
Sweet thanks for the tip.
We will have to keep an eye on it. Currently, the fabric version is not on Curse. Once it is, it looks like it will be called Refined Storage 2. Let's hope it is soon though. 
https://github.com/refinedmods/refinedstorage2

**Comment by Knuckels92** [comment]
Yeah, iam waiting for more informations on the Discord, the last Information for the Release on Curse was:" No eta on a cf release. To far away". :(

**Comment by itsdinkd** [comment]
Since we use Applied Energidticd 2 and toms storage, I'm going to have to say no but that doesn't mean it won't be on aqm4 if it feels right.
