### ISSUE TITLE
[BUG]Player crashes server when drinking health Pot

### ISSUE THREAD

**Issue by JLau03** [red2blue/AQM2#158]
**Modpack Version**
2.0.6

**Minecraft Version**
1.18

**Describe the crash or bug**
Player crashes server when drinking health Pot

**Steps to reproduce the behavior:**
Drink health pot, in or out of flan claim

**Expected behavior**
Not a server crash

**Screenshots**
Post screenshots if available

**Crash log or latest.log.log**
https://paste.corebot.dev/fagixekona.sql

**Additional context**
Any additional context?

**Comment by itsdinkd** [comment]
Developer has fixed. It's due to.mc dungeon artifacts. I will release an update to aqm2 in the coming days. 

You should be able to download it's update and place in your server/clients to fix in the meantime
