### ISSUE TITLE
[BUG] [Multiplayer] [1.18.1] AE2,TechReborn Rendering & Block updating

### ISSUE THREAD

**Issue by X-Niter** [red2blue/AQM2#161]
**Modpack Version**
2.0.6a

**Minecraft Version**
1.18.1

**Describe the crash or bug**
AE2 controllers and the AE2 ME system, in general, look like it stops updating the rendering, or stops updating entirely.
When this happens, the system was not useable; replacing ONE AE2 controller causes 2 controllers to update with "Active" rendering, which seems to make the AE2 ME system kinda work but with very buggy visuals. 
On single player, this issue does not exist, you can leave the chunks and come back and it still works, you can quit the single player world, join back and it all still works, this same thing also applied to the TechReborn wires, they work and render correctly on single player but not on multiplayer.
The bug is being reported here on the idea that it could potentially be a mod conflicting with each other inside the modpack, thus it wouldn't persay be AE2 or TechReborns concern; though this could be incorrect and it very well could be there concern 110%.
For the AE2 ME system, you can break and replace the whole ME system and it looks like it all runs and works for a little bit, but only for a little bit untill you leave the server, or go far away from the base.
The TechReborn cables, those are just straight broken, they have no connection poins at all and when placed they all palce seperatly, but not on single player, everything works in single player mode as stated above.

**Steps to reproduce the behavior:**
Running modpack as server, progress into AE2 and TechReborn, build your AE2 ME system, leave the chunk rendering distance, disconnect and reconnect, restart the server, something to get the chunks to reload, the AE2 system will be broken regarding functionality and rendering. 
TechRebron cabled; Just make some and place them, they will all place seperatly and won't render connection.

**Expected behavior**
AE2 ME System renders correctly, and functions fully.
TechRebron cabled when palced will actually connect together as they should.

**Screenshots**
AE2 Controllers
![AE2 Controllers](https://user-images.githubusercontent.com/30506033/156890988-c9e5dacf-571d-470c-bd26-354b1495592c.jpg)
TechReborn Wires
![Techreborn wires](https://user-images.githubusercontent.com/30506033/156890994-8d4f79c2-3d23-4b80-a444-a2edcfa4b52b.jpg)
Replacing one AE2 Controller
![Replacing one ae2 controller](https://user-images.githubusercontent.com/30506033/156891010-c428540f-17ba-416b-bf66-76988ebc0253.jpg)

**Crash log or latest.log.log**
[Generic Client Side log](https://pastebin.com/KhgkGmGi)
No crash log.

**Additional context**
To note* It's most likely a mod issue on AE2 and TechRebron's side of things, but worth coming here first on the stance that it affects the pack when running on a multiplayer instance.

**Comment by itsdinkd** [comment]
Could you test this on v2.1 and let me know if it still exists?

**Comment by X-Niter** [comment]
> Could you test this on v2.1 and let me know if it still exists?

Sure thing, it may take me some time, work and all, but I'll make sure to get back to you when we test it out on the 2.1+ version unless someone else tests it sooner then that.

**Comment by itsdinkd** [comment]
Closing under assumption it is fixed with last two releases. If it isn't, let me know and I will reopen.
