### ISSUE TITLE
[BUG] Multiple Issues

### ISSUE THREAD

**Issue by FooterManDev** [red2blue/AQM2#163]
**Modpack Version**
2.0.6a

**Minecraft Version**
1.18.1

**Describe the crash or bug**
REI: When hovering your curser over items, the game lags, When pressing R/U/MouseButtons on an item to see its uses or whatever, the game lags, and whenever REI is open anyway the game lags
Mobz: The entities in Mobz is completely unbalanced, there are random mobs spawning in places they shouldn't
Bosses: The Ender Dragon/Wither have random effects when spawned, which makes the entire fight unfair
Recipes: As in the other issue I did #162 the Tech Reborn ore blocks are broken, and the recipe for the Angel Ring item seems completely unfair to some players
Consistency Plus: This mod is awful, it makes it worse to gather blocks to build with or use in recipes, it adds another step which seems completely unnecessary, and the blocks don't even look that good
Crafting: When crafting any item, the game drops frames, usually when crafting in bulk.

**Steps to reproduce the behavior:**
REI: Hover over some things, right click them, whatever.
Mobz: Look for some random entities from this mod in completely random places, like an Ocean.
Bosses: Attempt to spawn a Wither, or go to a Dragon and see the effects.
Recipes: Craft the Tech Reborn raw ore blocks into Ingot blocks, and look at the Angel Ring recipe and think to yourself: what have I done?
Consistency Plus: Mine any block that the mod overrides and turns into its own block.
Crafting: Craft any item in single or bulk form.

**Expected behavior**
REI: Zero performance drops, for a mod that helps people find the recipes for things, wouldn't it make sense for it to never lag?
Mobz: Less Random mob spawns.
Bosses: Regular bosses that do not spawn with positive potion effects.
Recipes: Tech Reborn raw ores with no Ingot block recipe, and a less insane recipe for the Angel Ring.
Consistency Plus: Regular block drops, and this mod not in the mods folder.
Crafting: Regular Vanilla behavior.

**Screenshots**
Post screenshots if available

**Crash log or latest.log.log**
use pastebin.com for your log

**Additional context**
Honestly, I feel like the people who make this modpack should be better than this. I will be posting this link to others to add onto the things I have said.

**Comment by ogmon1243** [comment]
The fast-crafting options on the left of the crafting table gui are very slow as instead of manipulating your items instantly it does each item one by one. This is especially annoying when trying to use the spread feature as it makes you wait for each individual item to be spread out. In forge this all happens instantly so idk why this is happening in fabric.

**Comment by busterbrown1999** [comment]
Can you please open up multiple tickets this can help us get the issue to the mod creators if need be. Any suggestive changes can you please label under feature request.
