### ISSUE TITLE
Crafting Tweaks mod not Instant

### ISSUE THREAD

**Issue by ogmon1243** [red2blue/AQM2#164]
**Modpack Version**
2.0.6

**Minecraft Version**
1.18.1

**Describe the crash or bug**
When using the fast crafting options on the left of the crafting grid in a crafting table, items are manipulated individually instead of instantly. For example, when using the spread feature of the mod, the items are sorted one by one into the crafting slots instead of instantly spreading like it should. This makes crafting blocks very slow as you need to wait for the items to sort before crafting.

**Steps to reproduce the behavior:**
Put a stack or 2 of a block into a crafting table and click the middle button on the left of the gui while holding shift to do the spread feature. This also works with the "balance" feature.

**Expected behavior**
Items instantly get manipulated into their corresponding crafting slots

**Screenshots**
Post screenshots if available

**Crash log or latest.log.log**
use pastebin.com for your log

**Additional context**
I'm playing this modpack on a server so it may be a server side thing if this doesn't happen usually.

**Comment by itsdinkd** [comment]
I haven't done anything to intentionaly cause this. It's most likely a feature of the mod and I imagine it's to reduce packets sent which in turn reduce potential lag. Closing due to this
