### ISSUE TITLE
[BUG] Unable to create terrasteel

### ISSUE THREAD

**Issue by Infinityvy** [red2blue/AQM2#165]
**Modpack Version**
2.0.6a

**Minecraft Version**
1.18.1

**Describe the crash or bug**
I build the Terrasteel Agglomeration Plate, connected it to my mana pool via spark. Upon adding the required ingredients nothing happens. I triple checked. Everything seems to be correctly set up. Even in creative with infinite mana pool i was not able to get a reaction. Is terrasteel disabled?

**Steps to reproduce the behavior:**
How can someone replicate this bug/crash?
Attempt to create terrasteel using the Terrasteel Agglomeration Plate.

**Expected behavior**
What is the expected outcome?
It creates Terrasteel.

**Screenshots**
![2022-03-07_01 47 06](https://user-images.githubusercontent.com/17906831/156950203-f352269d-db31-4b27-8094-3c943f29a498.png)

**Comment by itsdinkd** [comment]
Closing as it was fixed in latest version of botania which is in aqm2 2.1
