### ISSUE TITLE
[BUG]Crash loop from mana spreaders

### ISSUE THREAD

**Issue by ShadowHenchman2** [red2blue/AQM2#167]
**Modpack Version**
What modpack version 2.0.6a

**Minecraft Version**
What mc version v18.1

**Describe the crash or bug**
after I placed a mana spreader on the hydro flowers it put me and my friend into a crash loop and always brings the abyss server down and are unable to join

**Steps to reproduce the behavior:**
How can someone replicate this bug/crash?
place a mana spreader on top of a hydro flower
**Expected behavior**
What is the expected outcome? most likely a crash loop

**Screenshots**
Post screenshots if available

**Crash log or latest.log.log**
use pastebin.com for your log

**Additional context**
Any additional context?
in the area where we have it it keeps crashing me and my friend

**Comment by itsdinkd** [comment]
Can you update to v2.1 of aqm2 and let me know if this bug still exists for you?
