### ISSUE TITLE
[1.4.2] [BUG] Fluid Tank rendering-related crash

### ISSUE THREAD

**Issue by slobodaapl** [red2blue/AQM2#17]
It appears some setting from Sodium (possibly culling of invisible blocks?) is causing an issue with Fluid Tank's Lead Tank, in our case filled with Modern Industrialization's Lubricant. It seems to be a crash related to the rendering of the block.

Crash log: https://pastebin.com/JHZM4mLz

**Comment by red2blue** [comment]
Nothing I can do unfortunately for this
