### ISSUE TITLE
Missing Recipes/items from REI [BUG]

### ISSUE THREAD

**Issue by qCastor** [red2blue/AQM2#170]
## **Modpack Version**
v2.1

### **Minecraft Version**
1.18.1

### **Describe the crash or bug**

After updating from v2.0.6a to v2.1:
Seemingly random recipes disappear from REI and are also uncraftable (these items were craftable last patch). It also seems to be
per person, as I am playing in a server. For example, the host could craft compressed quartz-crete, but I could not.

I repaired my mod profile thinking it could've been that, it seems that I can craft it now, but more that aren't working still that I have found are:
Emerald Gear
Kibe mob trap spikes (these are actually not showing at all in REI now)

I'll stumble across more I'm sure, and I'll update this post when I do, if it helps.

### **Steps to reproduce the behavior:**
How can someone replicate this bug/crash?

Not even sure what causes it to know how to replicate.

### **Expected behavior**
What is the expected outcome?

Being able to craft these items.

### **Screenshots**

Post screenshots if available

### **Crash log or latest.log.log**

use pastebin.com for your log

Too big for pastebin not sure what other site you trust to use, just let me know and I'll upload my log to that

### **Additional context**
Any additional context?

Playing in server (not localhost)

I tried completely deleting my profile and installing a fresh one, and the results are the same.

**Comment by itsdinkd** [comment]
Kibe spikes have always been disabled.  What else is missing?

**Comment by Cratios** [comment]
![Uploading 15D97D3F-F142-435F-A80B-420E0068F4F5.jpeg…]()

**Comment by Cratios** [comment]
Same issue here. For example if you type gobber in REI you don’t see images of the Block.

**Comment by veetus1** [comment]
If the issue is just invisible icons just delete the rei config in your folder. Fixed it for me.

**Comment by itsdinkd** [comment]
What veetus mentioned would fix it, or you can go into REI settings and disable cache rendering recipeb
