### ISSUE TITLE
[Feature Request] AE2Things 

### ISSUE THREAD

**Issue by darksoulpk68** [red2blue/AQM2#171]
-------------------------------------
**Is your feature request related to adding/removing a mod or is it a ingame suggestion.**

I'd like to suggest to add the mod AE2Stuff (AKA AE2Things), which adds a couple of items related to AE2. I'm a real fan of Automation with AE2, but I think the original way of making them is a bit annoying.

------------------------------------
**Why do we need this feature?**

The mod only adds the Advanced Inscriber and the Crystal Growth Chamber, but it also adds a new cell with Infinite types. I'd suggest to deactivate this last one because it removes all the fun from crafting multiple Disk drives and having many 64k drives.

-------------------------------------
**Link to the modpage if mod?**
This is required if you are suggesting a mod to add

https://www.curseforge.com/minecraft/mc-mods/ae2things

-------------------------------------
**Additional context**

I'd also enjoy the mod Extra Cells 2, but that's a 1.12 Forge mod and I wasn't able to find a 1.18 Fabric version of it

Thank you !

**Comment by Quadrum1** [comment]
I disagree with type limiting.
I don't see any fun in having entire drives full of 64k storage cells.

Mobs tend to drop lots of unstackable loot. 
The sheer number of both item type and items itself make the AE much less useful for storage.

In my opinion, having some infinite type cells would be a great QoL improvement, something desperately needed.

**Comment by darksoulpk68** [comment]
> The sheer number of both item type and items itself make the AE much less useful for storage.

As a long time AE2 enthusiast, the "difficulty" in having many cells due to type limitations is part of the fun. I do understand the problem with non-stackable items, and I'd be more than happy to have a sort of cell with a much higher number of non-stackable items.

Per example, let's say they would be like normal storage cells, but instead of having 63 types and X item storage, they'd have multiple tiers (let's say 100, 200, 500 and 100, just random numbers). They would only store non-stackable items with a high priority. However I think that'd be a dev job, as it would require to create more items. 

I'd say either that, or make a recipe tweak for the unlimited type drive to be way harder than usual. Otherwise I really think it removes a part of the fun in the original mod.

**Comment by Quadrum1** [comment]
I would fully support a higher cost for the unlimited-type drives

**Comment by itsdinkd** [comment]
The developers of AE2 do not support this mod due to the way it injects into ae2 and breaks things apparently.
