### ISSUE TITLE
[BUG] Crash Loop from Akashic Tome

### ISSUE THREAD

**Issue by Alvaerelle** [red2blue/AQM2#172]
**Modpack Version**
2.06a and  2.1

**Minecraft Version**
1.18.1

**Describe the crash or bug**
I Tried to use the akashic tomb after adding some books to it then when I tried to change it back to the akashic tomb it went to the server menu and said I couldn't connect, after that when I rejoined my world and tried it again my game crashed and crashes whenever I open it there were 4 books in it
Modern industrialization, croparia, end for dummies, and I don't remember that last one

**Steps to reproduce the behavior:**
I also made a copy of the world after the update and instead of automatically crashing it went to the server screen and said I had disconnected from the server even though I'm on single player beyond this i do not know

**Expected behavior**
for it to change back to akashic tome

**Screenshots**
[https://imgur.com/a/RWTWhMw](url)

**Crash log or latest.log.log**
https://paste-bin.xyz/42670 

**Additional context**
Any additional context?

**Comment by itsdinkd** [comment]
Delete the akashic tome. its really buggy I'm most likely going to remove from pack.
