### ISSUE TITLE
[BUG] The Botania Bellethorne is killing my companion bat

### ISSUE THREAD

**Issue by FederAndInk** [red2blue/AQM2#173]
**Modpack Version**
2.1/2.0.7

**Minecraft Version**
1.18.1

**Describe the crash or bug**
The Bellethorne from botania is killing my companion bat :cry: 

**Steps to reproduce the behavior:**
place a Bellethorne and a pool of mana and place a companion bat near it.

**Expected behavior**
It shouldn't kill my companion bat

**Screenshots**

https://user-images.githubusercontent.com/24270152/157849384-e04156f0-5b8b-491f-8857-11a4da052e7f.mp4

**Crash log or latest.log.log**
use pastebin.com for your log

**Additional context**
Maybe the entity could be blacklisted? But I couldn't find anything in the config files

**Comment by itsdinkd** [comment]
nope not blacklisted, i will report it botania though

**Comment by itsdinkd** [comment]
I believe this was fixed in 2.1.2 lmk if not and I will reopen
