### ISSUE TITLE
[BUG] Can’t repair Diamondtools in Anvil

### ISSUE THREAD

**Issue by Cratios** [red2blue/AQM2#174]
Modpack: AQM 2 Fabric
Version: 2.1

Problem: I can’t repair tools in the anvil. I put a Tool in the anvil, putting for example diamonds to repair it and the when I try to put out the repaired Tool it is gone. After looking in the anvil again the tool and the Diamonds are back in the inventory. But it isn’t repaired.

**Comment by FreshDoktor** [comment]
Same for other tools here by me. Game also has crashed two time when i tryed du put an item inside the anvil. Sadly i cant copy the text from the launcher log i hope the screen is enougth 
![grafik](https://user-images.githubusercontent.com/39657947/157940750-c4bd1474-289d-4a19-9b55-45b901ccea0f.png)

**Comment by FreshDoktor** [comment]
if i move the item with shift inside the anvil there is only an exception in the console if i try to move it manually inside the anvil the game crashes

**Comment by Cratios** [comment]
Since Update to 2.1.1 my Problem is solved
