### ISSUE TITLE
How to disable items to be shown big on the left side if I hover over them in my inventory?

### ISSUE THREAD

**Issue by JaWeRo00** [red2blue/AQM2#175]
If i hover over a item in my inventory, it's shown very big on the left side , which is quite annoying.
Can I disable this function?

**Comment by PWNYYY** [comment]
remove the mod `big-items-duh-1.1.1+mc1.18`

**Comment by itsdinkd** [comment]
Please do not ask for support in a issue tracker. That's what the discord is for.
