### ISSUE TITLE
[Feature Request] Update Additional Enchanted Miner to 18.6+

### ISSUE THREAD

**Issue by FreshDoktor** [red2blue/AQM2#176]
**Is your feature request related to adding/removing a mod or is it a ingame suggestion.**
Update Additional Enchanted Miner on current Version

**Why do we need this feature?**
An Fillere for bigger Terraforming projects would be nice. It was implementet on Version 18.6 of this mod. The modpack uses currently 18.2

**Link to the modpage if mod?**
[This is required if you are suggesting a mod to add](https://github.com/Kotori316/QuarryPlus)

**Comment by FreshDoktor** [comment]
Other blocks like the spawen controller should be removed because they are too strong

**Comment by itsdinkd** [comment]
That is the forge version, not the fabric version. Fabric version does not contain many features that the forge one has.
