### ISSUE TITLE
[BUG] Anvil makes Soul siphon 3 disappear/deletes it

### ISSUE THREAD

**Issue by GGOBI18** [red2blue/AQM2#177]
**Modpack Version**
What modpack version

2.1.2

**Minecraft Version**
What mc version

1.18.1

**Describe the crash or bug**

when you place a book enchanted with Soul siphon 3 in the most left side spot and try to take it out or back out of the anvil, the book gets deleted

**Steps to reproduce the behavior:**
How can someone replicate this bug/crash?

Get a book of Soul siphon 3 ( i dont know if level on enchanment matter) 
place it the anvil on the most left spot  
place another book or item in the other spot 
try to take the book of Soul siphon back in your inventory 
the book should disappear/get deleted 

**Expected behavior**
What is the expected outcome?

the book should disappear/get deleted 

**Screenshots**
i would post a video but i can get to crop it properly 

**Additional context**
i am playing on one of the official severs of Another quality modpack 2
unsure if that has to do with the bug

**Comment by itsdinkd** [comment]
is this fixed on 2.1.3?
