### ISSUE TITLE
[BUG] AppliedEnergistics meteors not spawning

### ISSUE THREAD

**Issue by PWNYYY** [red2blue/AQM2#179]

**Comment by veetus1** [comment]
Is it a bug? I just assumed the items acquired from the meteors were now acquired through Botania's mana pool. Maybe I'm wrong but as an alternative you can.

**Comment by BushTrocity** [comment]
> Is it a bug? I just assumed the items acquired from the meteors were now acquired through Botania's mana pool. Maybe I'm wrong but as an alternative you can.

I see where it says to do a quest in "What Sorcery is this" but said quest is not there and REI doesnt list the recipe for the botania craft.


![Screenshot 2022-03-18 052204](https://user-images.githubusercontent.com/3528732/158975968-54a91d64-a6e0-446d-bbcb-ee164513b810.png)
![Screenshot 2022-03-18 052216](https://user-images.githubusercontent.com/3528732/158975971-b075c533-110d-459b-8b4b-97e47fc44054.png)
![Screenshot 2022-03-18 052359](https://user-images.githubusercontent.com/3528732/158976203-4ce8de04-9dfb-474b-a451-95a178734c8f.png)
