### ISSUE TITLE
[Suggestion] Carnivores - Modded Food Compatabillity

### ISSUE THREAD

**Issue by fluX3R0** [red2blue/AQM2#181]
**Modpack Version**
Another Quality Modpack 2 - 1.18.1
release fabric-loader-013.3-18.1

**Minecraft Version**
1.18.1

**Describe the crash or bug**
Carnivores(Origins) are unable to eat food they logically should be able to within the modpack.

**Steps to reproduce the behavior:**
How can someone replicate this bug/crash?
Review the different foods on REI provided in the mods while been a character that is a pure carnivore.
Attempt to eat any of these foods.

**Expected behavior**
What is the expected outcome?
Carnivores(Origins) are able to eat additional modded fish based and other modded choices that aptly fit a pure Carnivore.

**Screenshots**
![image](https://user-images.githubusercontent.com/96419410/158636695-0ab8dde4-b513-4db2-8da2-90729444e162.png)

**Crash log or latest.log.log**
use pastebin.com for your log

**Additional context**
~How I fixed it for my server, I updated the JSON file here `Origins-1.18-1.3.1.jar\data\origins\tags\items`  the file meats.json 
To make this work locally, I found the mods that weren't compliant[gofish/valleycraft] and copied the tag names from:
`go-fish-1.4.1-1.18.1.jar\data\minecraft\tags\items`  &  `valley-craft-2.2.1-1.18.1.jar\data\minecraft\tags\items `
into the meats.json file within the origin mod.

As after reviewing the mods[origins] docs this is what it describes 
https://origins.readthedocs.io/en/latest/

The reason Croptopia and Better Animals Plus is working is it has a meat.json defined within it, the mod developers seemed to include this in that case, in these cases though you seem to then be able to eat a mix of foods.

Now you could define them in the smaller mods for your pack or in the main origin, from what I've found through my own testing anyway. Be careful with the things such as squid_sucker though as they're defined under misc in valleycraft and not under their tags list for fishing.

Happy to provide my meats.json file to save you some time if you want :)

**Comment by itsdinkd** [comment]
Not a bug but a suggestion to add modded food into origins tags. If you create a pull request in this github with your changes I will merge it
