### ISSUE TITLE
[BUG] Croparia Greenhouse/Farmer's Delight Rice Crash

### ISSUE THREAD

**Issue by WinterPhoenix-602** [red2blue/AQM2#183]
**Modpack Version**
2.1.2

**Minecraft Version**
1.18.1

**Describe the crash or bug**
I placed a Croparia greenhouse on some rice, and it crashed the Zion server.

**Steps to reproduce the behavior:**
Try placing a Croparia greenhouse on some Farmer's Delight rice.

**Expected behavior**
Crashing the game.

**Crash log or latest.log.log**
https://paste.corebot.dev/itorujodah.md

**Comment by itsdinkd** [comment]
Duplicate
