### ISSUE TITLE
[BUG] Croparia Crop Generator Crash

### ISSUE THREAD

**Issue by WinterPhoenix-602** [red2blue/AQM2#184]
**Modpack Version**
2.1.2

**Minecraft Version**
1.18.1

**Describe the crash or bug**
Croparia crop generator crashed the server.

**Steps to reproduce the behavior:**
Place a Croparia crop generator above a waterlogged glowstone slab surrounded by fully grown Croparia crops.

**Expected behavior**
What is the expected outcome?
Crashing the game.

**Crash log or latest.log.log**
https://paste.corebot.dev/oxajigonoj.md

**Comment by itsdinkd** [comment]
Can you reproduce in single player and send the crash log?

**Comment by WinterPhoenix-602** [comment]
> Can you reproduce in single player and send the crash log?

Here you go.
https://pastebin.com/QcuDEg7U

**Comment by itsdinkd** [comment]
Does it happen when it's not on a waterlogged glowstone slab?
