### ISSUE TITLE
[BUG] Polymorph does not work in furnaces

### ISSUE THREAD

**Issue by MelnCat** [red2blue/AQM2#186]
**Modpack Version**
2.1.2

**Minecraft Version**
1.18.1

**Describe the crash or bug**
Polymorph does not work on furnaces.

**Steps to reproduce the behavior:**
1. Attempt to smelt an item with a recipe conflict in a furnace (i.e eggs, obsidian, pridefin, bricks)
2. Try to switch the output to one from a conflicting recipe, and realise that there is no button for Polymorph.

**Expected behavior**
The Polymorph button appears, and switching the result of the conflicting recipe works as intended.

**Screenshots**
![image](https://user-images.githubusercontent.com/37024464/158932062-aea77e27-9e5c-4baf-bc53-f30bf3f30b15.png)
![image](https://user-images.githubusercontent.com/37024464/158932095-ddba2474-38f9-4648-bdf2-d2b8ac92735b.png)

**Crash log or latest.log.log**
I don't think it's relevant for this issue.

**Additional context**
Any additional context?

**Comment by itsdinkd** [comment]
Unfortunately nothing I can do. Use improved stations furnace if you want to use polymorph
