### ISSUE TITLE
[Bug] Eating with the soul devourer enchantment crashes the game

### ISSUE THREAD

**Issue by Karrtoffelbaer** [red2blue/AQM2#188]
Description: food is in the off hand, sword is enchanted with soul devourer from mcdw, when I eat, the game crashes.
[crash-2022-03-18_21.40.35-server.txt](https://github.com/itsdinkd/AQM2/files/8307565/crash-2022-03-18_21.40.35-server.txt)

**Comment by itsdinkd** [comment]
Please re-open this issue using the Template provided when selecting "Bug Issue"
