### ISSUE TITLE
Anvil item combining crash/not combining[BUG]

### ISSUE THREAD

**Issue by Matiss-Priednieks** [red2blue/AQM2#190]
**Modpack Version**
What modpack version
2.1

**Minecraft Version**
What mc version
1.18.1
**Describe the crash or bug**
When combining any two enchanted items game either crashes if not shift clicking items or if shift clicked items don't get combined and required XP is drained (until relog). Either way the two items are not combined. Happened on 2 enchanted diamond pickaxes, and 2 sapphire ones, haven't tested more since I don't have time nor patience for it.
Running on a server (6 cores + 24gb ram)

**Steps to reproduce the behavior:**
How can someone replicate this bug/crash?
Try combining two enchanted pickaxes, or 1 enchanted one non enchanted and this bug should appear.

**Expected behavior**
What is the expected outcome?
Combined pickaxe with combined enchantments

**Screenshots**
Post screenshots if available

**Crash log or latest.log.log**

https://pastebin.com/0pBxiaA0

**Additional context**
Any additional context?
As mentioned, on a linux server using the default server config with the exception of 24gb of ram allocated.

**Comment by Matiss-Priednieks** [comment]
To extend to this, issue also happens when trying to repair anything.

**Comment by itsdinkd** [comment]
Please update modpack before reporting bugs. This has been fixed.
