### ISSUE TITLE
[BUG] Bottemless Bundle (spectrum) Duplikation 

### ISSUE THREAD

**Issue by gohstflo** [red2blue/AQM2#192]
**Modpack Version**
AQM2-2.1.2 fabric

**Minecraft Version**
1.18

**you can duplicate the iteam and other iteam by placing the bag and destroy it then you got two bags with the same inventory**

**Steps to reproduce the behavior:**
place and destroy the bag

**Expected behavior**
it shulden only come one bag

**Screenshots**
.

**Crash log or latest.log.log**
.

**Additional context**
Any additional context?

**Comment by itsdinkd** [comment]
aware, waiting for dev to fix their latest update so I can update the modpack with it.
