### ISSUE TITLE
[BUG] -ME Interface Deleting Items-

### ISSUE THREAD

**Issue by MightyTitania** [red2blue/AQM2#195]
**Modpack Version**
AQM2-2.1.2

**Minecraft Version**
1.18.1 

**Describe the crash or bug**
Bug: ME Interface not keeping Its inventory on log in/log out.

**Steps to reproduce the behavior:**
Log out.... XD

**Expected behavior**
[ME interface with a Storage Bus attached to it]   An automated ME interface's top row (with a crafting card), is supposed to be set as the item that you want auto crafted. As long as that pattern is somewhere in your AE network, it will automatically try to make those items until the set number has been made, and then throw them on the second row. Which then can be accessed through the ME Interface its self, or the terminal. 

**Screenshots**

![2022-03-25_02 35 39](https://user-images.githubusercontent.com/101175075/160219589-6bc4e0d7-8116-46a7-82cf-cffee04cd038.png)

![2022-03-25_02 35 36](https://user-images.githubusercontent.com/101175075/160219601-dfa85d39-ddfc-4e66-917c-f80625c427f0.png)

![2022-03-25_20 26 37](https://user-images.githubusercontent.com/101175075/160219652-8defda32-0530-4f10-95b6-d8024e575812.png)

![2022-03-25_02 34 39](https://user-images.githubusercontent.com/101175075/160219801-7f71f828-0edb-4767-9d9b-a82bdd95f48d.png)

![2022-03-25_20 42 41](https://user-images.githubusercontent.com/101175075/160219813-2cd8595a-c6d8-4ec9-84c9-01a8c564416e.png)

**Additional context**
The wiring in back only connects the ME Interface back into the AE network. Upon logging in, all of the Interfaces are completely wiped, that also includes all the materials that those interfaces made and had stocked up on. I know for a fact this works, Its my second time making it.... and the second time my items were deleted. But as a side note, i have a ME Interface completely by itself and it works fine. Hasn't poofed like the other ones have... So im lost about this ;-:

**Comment by MightyTitania** [comment]
1st, 2nd, and 4th picture are right before logging off for the night, working perfectly fine. The 5th shows the same one with nothing done to it, and ample power supply, but everything is missing. The 3rd is the setup.

**Comment by itsdinkd** [comment]
Does this occur on 2.1.3?
