### ISSUE TITLE
[BUG] -Diamond Crack Hammer Dup.-

### ISSUE THREAD

**Issue by MightyTitania** [red2blue/AQM2#196]
**Modpack Version**
AQM2-2.1.2

**Minecraft Version**
1.18.1 me thinks

**What is the bug?**
![2022-03-25_20 58 59](https://user-images.githubusercontent.com/101175075/160220392-18323725-188d-4ab6-80e9-14f0ac032c03.png)

![2022-03-25_20 59 06](https://user-images.githubusercontent.com/101175075/160220396-4aa5dfea-913f-43c3-bd4e-065b4f5f9b77.png)

![2022-03-25_20 59 09](https://user-images.githubusercontent.com/101175075/160220397-b1ad91e0-83b7-48c6-b521-9d89be2f93bb.png)

You can dup. these crack hammers by putting them in to themselves with out eating the other up, those 3 that i made at the end but just from the two in the crafting table. As far as i tested, it only works with other crack hammers no dupping anything else.

**Comment by itsdinkd** [comment]
good to know however all i can do is report to the developer
