### ISSUE TITLE
DOOM Fabric Armor crashes game[BUG]

### ISSUE THREAD

**Issue by JaWeRo00** [red2blue/AQM2#197]
**Modpack Version**
AQM2-2.1.2

**Minecraft Version**
1.18.1

**Describe the crash or bug**
I crafted the "Praetor Doom chestplate", (swapped it with my enchanted diamond chestplate)/equipped it and the game/launcher crashed and every try to get back on the server was hopeless, because I got kicked after ~3 sec. The item is labeled with "Crafted by the Wretch for the Doom Slayers Conquest of the Nether" and made out of 5 Argent Plates and 1 Argend Energy.

If I had played in singleplayer my world would have been lost, because it would be impossible to get back on the server permanently. Thanks to the fact that I played with a friend on a multiplayer server he was able to spam "/kill Username", so in the short period of time of 3 secs while I was on the server I was killed and seperated from the cursed item. We had to destroy my gravestone so we avoid contact with the armor piece resulting in destroying all other items in my inventory as collateral damage.

**Steps to reproduce the behavior:**
-Craft the Preator Doom Chestplate
-Equip it at the chestplate slot

**Expected behavior**
What is the expected outcome?
-Game crashes

**Additional context**
No clue if other armor pieces of the doom farbic are bugged too. Also unknwon if the armor swap caused the crash to happen. I also had equipped a Dia helmet, iron boots, leggings of life (all enchanted), a bejeweled backpack and a magnet.

**Comment by itsdinkd** [comment]
Are you sure you didnt put it in a cosmetic slot because that is when it crashes, which is a bug with cosmetic slots. I could not reproduce.

**Comment by itsdinkd** [comment]
Please send me your crash log.  pastebin.com

**Comment by JaWeRo00** [comment]
I don't know where I can find the crash log, but I did further testing. With an empty chestplate slot the game doesnt crash, but if a chestplate is already equipped and you try to swap it with the preator doom chestplate, THEN THE GAME CRASHES

**Comment by itsdinkd** [comment]
Can't help without you posting a log. You can find crash logs in the crash report folder. I will reopen once that's uploaded
