### ISSUE TITLE
[BUG] "natural_stone" tag from "Origins" doesn't work

### ISSUE THREAD

**Issue by DerMuaaa** [red2blue/AQM2#199]
**Modpack Version**
2.1.3

**Minecraft Version**
1.18.1

**Describe the crash or bug**
The "natural_stone" tag from "Origins" doesn't work with this modpack, which leads to Feline or Shulk not working correctly. 
I "fixed" it by removing everything from KubeJS, but i dont know what it even does.

**Steps to reproduce the behavior:**
1. Start a new world
2. Select Feline or Shulk
3. Try to mine stone with a pickaxe and it won't have the "unbreakable" effect.
4. Also there is no tag on the right with F3 (See pic 1 and 2)

**Expected behavior**
The Stoneblock should not be mineable and there should be a "natural_stone" tag in the F3 interface.

**Screenshots**
![Without KubeJS Resource Pack](https://user-images.githubusercontent.com/102706922/160960429-a862ab64-99ad-430a-a92b-0552d5ccf73e.jpg)

![With KubeJS Resource Pack](https://user-images.githubusercontent.com/102706922/160960439-30be9b05-9c1d-4bd5-a90f-e22d96068c8e.jpg)

**Crash log or latest.log.log**
https://pastebin.com/4s8C3nR5
My guess is line 1733.

**Additional context**
I found out that there is a "Origins" conflict with "KubeJS Resource Pack", but this is as far as i could get with my knowledge.
![error](https://user-images.githubusercontent.com/102706922/160960685-af237288-d408-4e7a-bfcc-9b919bba7af3.jpg)

**Comment by DerMuaaa** [comment]
I fixed it by removing the tag from the other mod.

If you have the same issue, the tag is located here:

\ATLauncher\instances\AnotherQualityModpack21181\kubejs\data\origins\tags\blocks\natural_stone.json

Just remove the "graveyard:tg_sandstone" and it should work.

**Comment by itsdinkd** [comment]
> I fixed it by removing the tag from the other mod.
> 
> If you have the same issue, the tag is located here:
> 
> \ATLauncher\instances\AnotherQualityModpack21181\kubejs\data\origins\tags\blocks\natural_stone.json
> 
> Just remove the "graveyard:tg_sandstone" and it should work.

So are you saying there is a invalid tag in the tag list and removing that fixed the issue?

**Comment by DerMuaaa** [comment]
Yes and so far there were no other related issues.
