### ISSUE TITLE
[BUG] Complete Quest Locate Biomes - Craft Nature's Compass 1.4.3

### ISSUE THREAD

**Issue by Antoninecek** [red2blue/AQM2#20]
**Modpack Version**
1.4.3

**Minecraft Version**
1.18.1

**Describe the bug**
Can't accomplish quest from Quest Book "Locate Biomes - Craft Nature's Compass". 

Can't Move items (click on plus button) from recipe (REI) of Nature's Compass to crafting table (server error  [Netty Server IO #4/WARN]: Received invalid START packet for SplitPacketTransformer with packet id roughlyenoughitems:move_items for side C2S). When crafted from ae2 terminal the Quest Book can't see it in inventory nor in hopper attached to quest block.

**Comment by red2blue** [comment]
Known issue
