### ISSUE TITLE
[BUG] Moth glitching into blocks after respawning

### ISSUE THREAD

**Issue by chloecoding-git** [red2blue/AQM2#201]
**Modpack Version**
2.1.3

**Minecraft Version**
Latest one

**Describe the crash or bug**
Upon death with the Moth Origin - unsure if this impacts other origins as well that have this function - whether you have the four arms wall climbing power enabled or disabled, when you respawn you will be glitched and unable to climb up and down blocks, and only momentarily stick into the block before the game pushes you back out.
So far only two solutions I have found:
1.) Disconnect and reconnect from the server, this one seems to have a 100% working rate.
2.) Reclaim grave, this one seems to be 50/50 as to if the glitching effect will continue afterwards or disappear.

**Steps to reproduce the behavior:**
1.) Have moth origin
2.) go into combat with mob and die
3.) respawn
4.) attempt to climb a wall, block, crafting table, or similar
5.) experience your character trying to glitch into the block instead of move up it.

**Expected behavior**
Climb up whatever block I am running at.

**Screenshots**
No screenshots I can grab.

**Crash log or latest.log.log**
No crash log, as it never crashes.

**Additional context**
Only started to experience it as of the 2.1.3 update.

**Comment by chloecoding-git** [comment]
UPDATE COMMENT: Found other method to unglitch after death - spamming the space bar to trigger the elytra wings for gliding seems to offer 75/25 chance currently for fixing this as well.

**Comment by itsdinkd** [comment]
Nothing I can do to fix this unfortunately. This is a problem with the mod that the developer would have to fix.
