### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Migice59** [red2blue/AQM2#203]
**Modpack Version**
The latest version of the modpack

**Minecraft Version**
1.18.1

**Describe the crash or bug**
The Phantom keeps suffocating whenever I go into walls and stuff the role is almost usless for the most part is there a way to fix it or a mod that's doing it?

**Steps to reproduce the behavior:**
Just play as phantom and turn into phantom mode then try to go underground.

**Expected behavior**
You don't suffocate as phantom the hole point is to walk through walls and what not to just die.

**Screenshots**
 
![Screenshot (1536)](https://user-images.githubusercontent.com/102924773/161446293-5448059b-38b4-4bea-92ec-5f0aaec444f1.png)

**Comment by ShortShowname** [comment]
This used to happen on a server I was in before and it's also happening on Zion (Probably Abyss too, I haven't joined though). I at least know that for this to be fixed the Lithium configs folder needs to be edited. This line needs to be added:
`mixin.entity.collisions.suffocation=false`
Hopefully this gets fixed soon. The owner of the old server I was in had to manually add the line every time the pack got updated.

**Comment by itsdinkd** [comment]
Phantom is disabled by default. I will not be adding this in.
