### ISSUE TITLE
[BUG] Chopping down Spectrum Tree with Gobber Tree Axe

### ISSUE THREAD

**Issue by Flixp** [red2blue/AQM2#207]
Modpack Version
2.1.3

Minecraft Version
1.18.1

What happens;
If you chop down one of the dyed trees from spectrum with a Gobber Tree Axe, you get only one colored log and multiple oak logs instead of the other (expexted) colored logs.

What is supposed to happen:
You get colored logs instead of oak logs.

Use Gobber Tree Axe on a colored tree from spectrum.

**Comment by itsdinkd** [comment]
Duplicate of #91
