### ISSUE TITLE
HQM Problems

### ISSUE THREAD

**Issue by Sphinx2k** [red2blue/AQM2#21]
Modpack Version
1.4.3
Minecraft Version
1.18.1
Describe the bug
Quest: Craft a Baby Backpack
-> Manual Submit doesn't work. Pumping with hopper in QDS does nothing, it stays in the hopper.

Quest: Locate Biomes
"Manual detect" button is not working. The compass is not detected and the quest cant be completed. 

Tested both in singe Player and on self hosted multiplayer server.

**Comment by red2blue** [comment]
Known issue
