### ISSUE TITLE
[BUG] Mining dimensions quest doesnt give a working reward

### ISSUE THREAD

**Issue by AlinaStarkova** [red2blue/AQM2#210]
**Modpack Version**
2.1.3

**Minecraft Version**
1.18.1

**Describe the crash or bug**
the quest reward for the Mining Dimension Quest is broken and gives an item that is "missing"

**Steps to reproduce the behavior:**
Do the quest, select the reward

**Expected behavior**
a random weapon

**Screenshots**
![image](https://user-images.githubusercontent.com/40489693/162679754-fec70943-cb98-4e3a-869a-c6da984f9e5d.png)
![image](https://user-images.githubusercontent.com/40489693/162679764-79fe1d8e-24ed-41d5-812e-e6324fad9ccf.png)

**Crash log or latest.log.log**
wasnt a crash

**Additional context**
was on Zion official server

**Comment by itsdinkd** [comment]
Fixed
