### ISSUE TITLE
[BUG] Game crashing while spectrum skull is equiped in cosmetc helmet slot

### ISSUE THREAD

**Issue by Flixp** [red2blue/AQM2#212]
**Modpack Version**
2.1.3

**Minecraft Version**
1.18.1

**Describe the crash or bug**
Every time you open your inventory after you equipped a spectrum skull in the cosmetic helmet slot (from the "cosmetic armor" mod) the game crashes/closes without error message. (i think when you look at someone with the skull as helmet too)

I reported this bug at the spectrum issue page aswell (no idea what the right place is)

edit: F5 crashes game too (I assume seeing another player with the bug does the same?)

**Steps to reproduce the behavior:**
Equip spectrum skull in cosmetic helmet slot

**Expected behavior**
Game not crashing

**Mod version**
spectrum: v1.2.8-1.18.1-midgame9
cosmetic armor: v1.2.1

If it is a crash bug add your crash log here
[crash-2022-04-11_19.10.28-client.txt](https://github.com/itsdinkd/AQM2/files/8466446/crash-2022-04-11_19.10.28-client.txt)
[crash-2022-04-11_19.24.34-client.txt](https://github.com/itsdinkd/AQM2/files/8466447/crash-2022-04-11_19.24.34-client.txt)

**Comment by itsdinkd** [comment]
This is an issue with cosmetic armor and the developer is MIA
