### ISSUE TITLE
Chunkloading [Feature Request]

### ISSUE THREAD

**Issue by SirSleepySimon** [red2blue/AQM2#213]
**Is your feature request related to adding/removing a mod or is it a ingame suggestion.**

When trying to automate processes leaving the area means everything will pause. So would like to have some kind of Chunkloader mod.

**Why do we need this feature?**

The only chunkloader I can currently find is the Industrial Chunkloader from Tech Reborn after spending the large amount of effort to make it, it seems to not work. So having a way to load chunks would be useful.

**Comment by busterbrown1999** [comment]
Chunk loading is disabled by default. You can enable it through the configs.
