### ISSUE TITLE
[BUG] Applied Energistics 2 / Meteorite Compass not working

### ISSUE THREAD

**Issue by HadesCrow** [red2blue/AQM2#214]
**Modpack Version**
2.1.3

**Minecraft Version**
1.18.1

**Describe the crash or bug**
No matter where im going my Meteorite Compass is just spinning. I cant find Meteorites and none of us have seen a Meteorite yet too. Its like there are no Meteorites existing. I have tried it on me and my friends server as well as in singleplayer and its always the same.

**Steps to reproduce the behavior:**
I took the origin Deer, the class Blacksmith and no curse/blessing. Just take a Meteorite Compass in your hand.

**Expected behavior**
The Meteorite Compass starts spinning no matter where you go. It wont show the direction to a Meteorite (if there are any Meteorites at all).

**Screenshots**
It would take a video to show it, so no.

**Crash log or latest.log.log**
No crash, just a bug.

**Additional context**
nothing

**Comment by itsdinkd** [comment]
Meteorites do not work. You need to craft the presses and skystone using botania. There are recipes for everything you need.

**Comment by HadesCrow** [comment]
Oh Thanks
