### ISSUE TITLE
[BUG] AE2 Crafting Status Screen crash

### ISSUE THREAD

**Issue by WinterPhoenix-602** [red2blue/AQM2#216]
**Modpack Version**
2.1.3

**Minecraft Version**
1.18.1

**Describe the crash or bug**
I was checking the status of a crafting Modern Industrialization steel drill when my game crashed.

**Steps to reproduce the behavior:**
Build an AE system and have it try to craft something.

**Expected behavior**
The game will crash.

**Crash log or latest.log.log**
[Crash Report](https://pastebin.com/uiYqVxe6)

**Comment by itsdinkd** [comment]
Not much I can do unfortunately. I would recommend try using different screen resolutions, and gui scales to see if it still crashes
