### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by darkspyro92** [red2blue/AQM2#217]
**Modpack Version**
2.1.1

**Minecraft Version**
1.18.1

**Describe the crash or bug**
Overlord skeletons not spawning.

**Steps to reproduce the behavior:**
Insert the recipe for a skeleton following the Overlord guide. Does nothing. 

**Expected behavior**
A skeleton should spawn.

**Screenshots**
![image](https://user-images.githubusercontent.com/22324730/163481616-beb0e961-8e04-46b6-9ff9-8d7c7383dd74.png)
![image](https://user-images.githubusercontent.com/22324730/163481633-8970b0b1-d656-4d12-bd87-bab8bd869985.png)

**Crash log or latest.log.log**
use pastebin.com for your log

**Additional context**
I asked on the Overlord mod and they said you changed the recipe for a skeleton. I'd like to know the recipe if that's true.

**Comment by itsdinkd** [comment]
Not a bug. Use REI to get the recipe. Please do not use github for support. That is what our discord is for

**Comment by darkspyro92** [comment]
Rei doesn't seem to have a recipe. 
![image](https://user-images.githubusercontent.com/22324730/163494541-13e7c243-b557-492e-9c92-ac8df3111d5d.png)
I see the caskets, crosses, graves, blood-soaked soil, a spawn egg which is something I can't get, and the order wand.

Edit: Searched just Skeleton as well with no luck.
![image](https://user-images.githubusercontent.com/22324730/163494650-a541443b-fcf1-4efe-8703-65b38fd79926.png)
