### ISSUE TITLE
[Feature Request] Earthbounds mod for AQM2

### ISSUE THREAD

**Issue by Klyser8** [red2blue/AQM2#218]
**Is your feature request related to adding/removing a mod or is it a ingame suggestion.**
Yep, it's a request to add a mod I created to the modpack.

**Why do we need this feature?**
Though the modpack's focus isn't exactly to keep the vanilla feeling of Minecraft intact, I think that Earthbounds would still be a good minor addition to the modpack. Feel free to take a look at the mod page and see for yourself if it's worth your time or not :)

**Link to the modpage if mod?**
https://www.curseforge.com/minecraft/mc-mods/earthbounds

**Comment by itsdinkd** [comment]
Added
