### ISSUE TITLE
Botania Items unbann

### ISSUE THREAD

**Issue by Youtrial** [red2blue/AQM2#219]
I found many banned Items in the modpack. Some of these items are Botania items like the Fruit of Grisaia or the Sword of the Kins Law which are normally obtainable by killing the Gaia Guardian. I really like these items and hope you can bring them back. If you have banned them because of being too op I can tell you they aren't. These items are endgame Items for which you have to kill the Gaia Guardian which is a really hard Boss and have to go through complete Botania to be able to summon him and even then you can get only one item every time so you need luck to get the right for which you have to kill him several times. Another item which I have found was the Tiara Wings. They are totally not op as you only can fly like with jetpacks and only for a short time so I don't understand why they are banned. If they are op then the Elytra should be also banned as people are causing massive lags with them and they are not banned. I hope these arguments will make you unbann the Botania items again.

**Comment by itsdinkd** [comment]
For any suggestion or request please use the feature request issue template that is provided when you start a new issue. 

I will not re-enable these items, though you are more than welcome to enable them yourself through the config and editing the kubejs files
