### ISSUE TITLE
[BUG] Shulk Natural Stone Mining Broken

### ISSUE THREAD

**Issue by TheSheev** [red2blue/AQM2#220]
**Modpack Version**
2.1.3

**Minecraft Version**
1.18.1

**Describe the crash or bug**
Shulks can no longer break stone with their hands as outlined in #199 

**Steps to reproduce the behavior:**
Install a fresh instance of AQM2, start a new character and set them as shulk. Attempt to mine stone. Does not drop cobble as it's suppose to.

**Expected behavior**
Mining works on stone as if pickaxe was in hand.

**Screenshots**
See #199 

**Crash log or latest.log.log**
N/A

**Additional context**
N/A

**Comment by itsdinkd** [comment]
#199
