### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by KingMusicManz** [red2blue/AQM2#221]
**Modpack Version**
AQM2-2.1.3

**Minecraft Version**
1.18.1

**Describe the crash or bug**
Unable to equip Artifality artefacts in their associated trinket slots; I.E; can't put ukelele on back, can't put baloon on head.

**Steps to reproduce the behavior:**
Try and equip an Artifality artefact on it's associated slot, in a server.

**Expected behavior**
That the item is equipped, and it's listed effects occur.

**Additional context**
Thanks for the help!

**Comment by Pedigruu** [comment]
The ukelele  is equipable in the offhand slot.
