### ISSUE TITLE
[BUG] the seed won't change

### ISSUE THREAD

**Issue by MJGjensen** [red2blue/AQM2#222]
**Modpack Version**
AQM2-2.1.3

**Minecraft Version**
1.18.1

**Describe the crash or bug**
I tried to create a new world but soon realised it was the same map like the one I'm already playing on. So I tried to make a second and third new one this time with a seed in it both with words and numbers
Before i saw this i did create a world before i tried different things to see why i would get the same world all the time.

**Steps to reproduce the behaviour:**
Do hope others don't have it

**Screenshots**
My main world
![Main World](https://user-images.githubusercontent.com/46543480/164727370-9e93a339-464e-4747-86e8-8b5aec1d7c36.jpg)
The world i created with letters in the seed
![Letter seed](https://user-images.githubusercontent.com/46543480/164727426-4016a02a-e5ed-4129-9f4b-fd9e05aad1e6.jpg)
The world i crated with numbers
![Nr seed](https://user-images.githubusercontent.com/46543480/164727518-7f7f479f-4951-472c-8da1-0b099d48cd79.jpg)

**Comment by itsdinkd** [comment]
you need to change the seed in kubejs/data/minevraft/dimensions/overworld.json 

please search for your issue before posting about it
