### ISSUE TITLE
aluminium from the moon cant be used [Feature Request]

### ISSUE THREAD

**Issue by lolboll04** [red2blue/AQM2#224]
the aluminium from Space Dimensions mod cant be used for anything more than aluminium blocks

so if you want to use it as any other aluminium in the mod you cant in any way

**Comment by itsdinkd** [comment]
Please follow the template that is given when creating a new issue by selecting Feature Request.

**Comment by itsdinkd** [comment]
You can use Tech reborn aluminum for everything but Space dimension, and visa versa.
