### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Aclerr** [red2blue/AQM2#225]
**Modpack Version**
2.1.3

**Minecraft Version**
1.18.1
**Describe the crash or bug**
When entering the world, lags begin, from 0 fps to 10. Previously, this was solved by rebooting, but now nothing helps

**Steps to reproduce the behavior: Enter the world xd**
How can someone replicate this bug/crash?
Idk
**Expected behavior**
What is the expected outcome?
It was 120 fps, now it drops to 10 every couple of seconds
**Screenshots**
Post screenshots if available

**Crash log or latest.log.log**
use pastebin.com for your log
https://pastebin.com/p4asWqMT
**Additional context**
Any additional context?
![2022-04-29_16 51 56](https://user-images.githubusercontent.com/104625786/165925901-8c46322d-8730-47f1-b1cc-0a6cd21fc336.png)
![2022-04-29_13 51 03](https://user-images.githubusercontent.com/104625786/165925908-0b7c8aea-e7f8-45ed-a1a8-4fd7f19e0787.png)

**Comment by itsdinkd** [comment]
Where is the bug? Performance on a server is not a bug
