### ISSUE TITLE
[BUG][quests] The Modern industrialization/Tech reborn and Deep mob learning quests are missing outside the official servers

### ISSUE THREAD

**Issue by FederAndInk** [red2blue/AQM2#227]
**Modpack Version**
2.1.3/4

**Minecraft Version**
1.18.1

**Describe the crash or bug**
The Modern industrialization/Tech reborn and Deep mob learning quests aren't included in the curseforge files and are only on the official servers

**Steps to reproduce the behavior:**
open the quest book and look at the side bar

**Expected behavior**
we need all the quests :D
don't want to miss a piece of wonderfully crafted quests

**Screenshots**

## On the official server:

![image](https://user-images.githubusercontent.com/24270152/166154141-8937abd0-ee0b-4d22-9fdc-eb84370fc862.png)

## On SP or unofficial servers:

![image](https://user-images.githubusercontent.com/24270152/166154168-f475a536-6130-441a-a97c-9801e5028360.png)

**Crash log or latest.log.log**
No need, I think

**Additional context**
Any additional context?
Nope

**Comment by FederAndInk** [comment]
ok, just noticed its only on the donor server. but still ^^

**Comment by busterbrown1999** [comment]
Donor server has access to unreleased quests

**Comment by FederAndInk** [comment]
ok, wasn't aware of that, sorry :|
