### ISSUE TITLE
[BUG][quests] The "starting botania" quest shouldn't require and give 'livingwood' but 'livingwood log' instead

### ISSUE THREAD

**Issue by FederAndInk** [red2blue/AQM2#228]
**Modpack Version**
2.1.4/1.0b

**Minecraft Version**
1.18

**Describe the crash or bug**

the quest require blocks made with the pure daisy flower like the livingrock and the derivative of livingwood log -> livingwood

livingwood is for decorative purpose, the actual block made from log with the pure daisy is the livingwood log.

**Steps to reproduce the behavior:**
open the quest book in the "What sorcery is this" panel and open the second quest of botania

**Expected behavior**
the quest should require and give livingwood log

**Screenshots**

## actual quest with decorative livingwood

![Screenshot_20220501_192345](https://user-images.githubusercontent.com/24270152/166157475-c4b1785e-16b2-44ef-a43a-6622d0687a5e.png)

## the craft of livingwood decorative block

![Screenshot_20220501_192352](https://user-images.githubusercontent.com/24270152/166157618-9eeebeef-15af-41de-9fa0-f856976a3d2b.png)

![Screenshot_20220501_192357](https://user-images.githubusercontent.com/24270152/166157703-a3618f77-6a07-41d3-9a05-bb5cc10db4c3.png)

## the useful livingwood log

![Screenshot_20220501_192414](https://user-images.githubusercontent.com/24270152/166157613-6cf77f9b-af9f-4cad-80ee-10c54853b343.png)

**Crash log or latest.log.log**
use pastebin.com for your log

**Additional context**
Any additional context?

**Comment by itsdinkd** [comment]
Fixed

**Comment by FederAndInk** [comment]
thanks :D
