### ISSUE TITLE
[BUG] Fairy race suddenly Missing.

### ISSUE THREAD

**Issue by Dres-Tiefling** [red2blue/AQM2#229]
**Modpack Version**
1.18.2 (Bouji server)

**Minecraft Version**
1.18.2

**Describe the crash or bug**
II logged in on 5/1/22 at 10pm est as fairy race and noticed I was regular sized without any powers. Sebas (mod) turned me human then fairy and no return to function. Sebas provided origin orb and fairy was not an option on list. 

**Steps to reproduce the behavior:**
How can someone replicate this bug/crash?
Sebas confirms its not on his list either.

**Expected behavior**
To have the fairy origin with all its powers and be small.

**Screenshots**
Post screenshots if available

**Crash log or latest.log.log**
use pastebin.com for your log

**Additional context**
Any additional context?
The morning of 5/1/22 I was a fairy up until 1:15pm when I logged off for work. This was after the intigration with discord and was still a fairy.

**Comment by itsdinkd** [comment]
It's disabled
