### ISSUE TITLE
[BUG] Mothling can't eat almost any food 

### ISSUE THREAD

**Issue by thatDifferent** [red2blue/AQM2#230]
**Modpack Version**
1.0b

**Minecraft Version**
1.18.2

**Describe the crash or bug**
Moth origin can't eat any type of food. Apples, carrots, sweet berries and beetroot are the only that I noticed can be eaten, even though it should be able to eat any type of vegetarian foods

**Steps to reproduce the behavior:**
Try to eat something apart apple, carrot,sweet berries or beetroot when having moth origin 

**Expected behavior**
Being able to eat vegetarian foods

**Comment by itsdinkd** [comment]
This isn't a bug but a feature request.
