### ISSUE TITLE
[BUG] [1.4.3] Block of citrine look up  in Spectrum book

### ISSUE THREAD

**Issue by Antoninecek** [red2blue/AQM2#24]
**Modpack Version**
1.4.3
**Minecraft Version**
1.18.1
**Describe the bug**
Mined citrine block and tried to look it up (by ctrl key) in Spectrum book. I don't have advancement of finding it, so maybe the page is still locked.

**To Reproduce**
1. Mine Block of Citrine for the first time
2. hold ctrl in inventory on it
3. client crash

**Crash log or latest.log.log**
[*crash log*](https://pastebin.com/kZu0ywrm)
[*latest*](https://pastebin.com/a0jUkXCs)

**Comment by red2blue** [comment]
known bug
