### ISSUE TITLE
[BUG] [1.4.3] Anvil crushing large citrine bud

### ISSUE THREAD

**Issue by Antoninecek** [red2blue/AQM2#25]
**Modpack Version**
1.4.3
**Minecraft Version**
1.18.1
**Describe the bug**
Throw Large Citrine Bud on ground and place anvil above it (4 blocks). Server crashed.

**Crash log or latest.log.log**
[*crash log*](https://pastebin.com/BnTW5h03)

**Comment by red2blue** [comment]
should probably report this to spectrum, not here.
