### ISSUE TITLE
[BUG] [1.5] Server crash on player connection after update

### ISSUE THREAD

**Issue by Antoninecek** [red2blue/AQM2#26]
**Modpack Version**
1.5
**Minecraft Version**
1.18.1
**Describe the bug**
Update server from 1.4.3 to 1.5. Start server. Player connect. Server crash.

**Crash log or latest.log.log**
[crash log](https://pastebin.com/CCgBx19R)

**Comment by red2blue** [comment]
Released hotfix. Issue was with most recent version of structure tools. 

get latest server pack at https://www.curseforge.com/minecraft/modpacks/another-quality-modpack-2/files/3585283
