### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Sphinx2k** [red2blue/AQM2#27]
**Modpack Version**
1.18.1-1.5-hotfix
**Minecraft Version**
18.1
**Describe the bug**
The download url in the server-setup-config.yaml has a typo. So downloading the server files after running startserver.sh did not work.

it reads ttps://media.forgecdn.net/files/3585/279/AQM2-1.18.1-1.5-hotfix.zip
the h of https is missing

**Comment by red2blue** [comment]
Fixed
