### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by OpenButter** [red2blue/AQM2#28]
**Modpack Version**
1.3.1
**Minecraft Version**
1.18.1
**Describe the bug**
Item pipes and fluid pipes from MI don't work for quarry plus.

**To Reproduce**
connect an applicable pipe to a quarryplus machine

**Expected behavior**
Should connect

**Additional context**
I don't know if it is intended to work with them. However, if not maybe ya'll should add some sort of mod that has pipes in it to be able to transport items or fluid around?

**Comment by red2blue** [comment]
Quarry Plus uses TR energy
