### ISSUE TITLE
[BUG] Server crash 

### ISSUE THREAD

**Issue by talianab** [red2blue/AQM2#62]
**Modpack Version**
1.60
**Minecraft Version**
1.18.1
**Describe the bug**
Locally hosted server crashes when I get into the game, I was afk when this happened the first time and when I join it just crashes and creates an error report file 

**To Reproduce**
1. Start the server 
2. Wait till its fully on
3. Join the server 
4. *Crash*
5. boot loop

**Expected behavior**
being able to join the server without crashing

**Screenshots**
N/A

**Crash log or latest.log.log**
https://pastebin.com/rk690fMb

**Additional context**
I increased the max tick to be safe but that did not solve the issue (now set to 6000000)

**Comment by itsdinkd** [comment]
You having a ticking enttiy from wandering llama. Most likely due to you not being on the hotfix with latest RPGStats version. Either update, or download erroring entity remover and put it in your server mods folder
